spring:

  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/empmsexam

    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9000
